#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if command -v podman > /dev/null; then
    DOCKER=podman
elif command -v docker > /dev/null; then
    DOCKER=docker
else
    echo "Neither podman nor docker are available" >&2
    exit 1
fi

"$DOCKER" run -it --rm -v "$SCRIPT_DIR:/demo" revng-demo "$@"
