#!/usr/bin/env bash

set -euo pipefail

if command -v podman > /dev/null; then
    DOCKER=podman
elif command -v docker > /dev/null; then
    DOCKER=docker
else
    echo "Neither podman nor docker are available" >&2
    exit 1
fi

"$DOCKER" build -t revng-demo .
./container /demo/run-all-examples
