#!/usr/bin/env bash

set -euo pipefail

cd /demo

for EXAMPLE in $(find -mindepth 1 -maxdepth 1 -type d -regex '\./[0-9]+-.*'); do
    echo "Running example $EXAMPLE" >&2
    pushd "$EXAMPLE" >& /dev/null
    ./run
    popd
done
