#!/usr/bin/env bash

set -euo pipefail

if ! test -d "/demo"; then
    echo "/demo not available" >&2
    exit 1
fi

TARGET="$1"
shift

ARTIFACT=cleanup-ir

cd "/demo/$TARGET"
clang-16 -fno-stack-protector source.c -o binary $(cat flags)

rm -rf resume/
revng \
    artifact \
    --enable-remote-debug-info \
    "$ARTIFACT" \
    --analyze \
    binary \
    --resume resume \
    -o /dev/null \
    --progress

if test -d "analysis"; then
    pushd analysis >& /dev/null
    for ANALYSIS in *.cpp; do
        NAME="${ANALYSIS/.cpp/}"
        g++ \
            -o "lib$NAME.so" \
            -fPIC \
            -shared \
            -O2 \
            "$ANALYSIS" \
            $(llvm-config-16 --cxxflags --ldflags) \
            -g

        opt-16 \
            -load-pass-plugin="./lib$NAME.so" \
            -passes="$NAME" \
            ../resume/"$ARTIFACT"/module.ll \
            -o /dev/null
    done
    popd >& /dev/null
fi
