#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -euo pipefail

cd "$SCRIPT_DIR"

# Compile to binary, with optimizations, but disabling stack protector and
# optimizations around tail calls, to ease source-to-binary matching for demo
gcc -O2 -fno-stack-protector -fno-optimize-sibling-calls use-after-free.c -o use-after-free.bin

# Lift with revng generate all decompiled C code in a single tar.gz, and unpack it in a single directory
revng artifact --debug-names emit-recompilable-archive --analyze use-after-free.bin -o - | tar xfz -

# Invoke clang-static-analyzer on the decompiled C code
clang-16 -Wno-int-conversion -o /dev/null -c decompiled/functions.c --analyze -ffreestanding \
  -Xanalyzer -analyzer-disable-checker -Xanalyzer deadcode \
  -Xanalyzer -analyzer-output=html -o clang-static-analyzer-results
