#!/usr/bin/env bash

set -euo pipefail

# Compile to binary, with optimizations, but disabling stack protector and
# optimizations around tail calls, to ease source-to-binary matching for demo.
# Also disable loop unrolling to enable showing array recovery.
clang-16 -O2 -Wno-pointer-bool-conversion -fno-stack-protector -fno-optimize-sibling-calls -fno-unroll-loops linked-lists.c -o linked-lists.bin

# Lift with revng generate all decompiled C code in a single tar.gz, and unpack it in a single directory
revng artifact emit-recompilable-archive --analyze linked-lists.bin -o - | tar xfz -
