#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${SCRIPT_DIR}/../common"

cd "$SCRIPT_DIR"

"${CLANG}" -O2 -fno-stack-protector source.c -o binary

rm -rf resume/
revng \
    artifact \
    --enable-remote-debug-info \
    "cleanup-ir" \
    --analyze \
    binary \
    --resume resume \
    -o /dev/null \
    --progress
