#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${SCRIPT_DIR}/../common"

cd "$SCRIPT_DIR"

RESUME_DIRECTORY="resume-directory"
BINARY="add-or-shift"

# Produce assembly
gcc -masm=intel -O1 -fno-inline -fno-asynchronous-unwind-tables -fno-exceptions -no-pie "${BINARY}".c -nostdlib -S -o "${BINARY}".S

# Compile
gcc -O1 -fno-inline -no-pie "${BINARY}".c -nostdlib -o "${BINARY}"
FUNCTION="local_0x$(address_of add-or-shift add_or_shift):Code_x86_64"

# Lift the binary with revng
rm -rf "${RESUME_DIRECTORY}"
revng artifact cleanup-ir --resume="${RESUME_DIRECTORY}" -o /dev/null "${BINARY}" --analyses=revng-initial-auto-analysis,revng-c-initial-auto-analysis

# Extract the cleaned up LLVM IR.
# At this stage the obfuscation is still present
zstdcat "${RESUME_DIRECTORY}"/cleanup-ir/module.bc.zstd | \
  # extract the function we want, and some of its surrounding
  "${LLVM_EXTRACT}" --func="${FUNCTION}" -S | \
  grep define -A 1000000 | grep -B 10000 '^}' | \
  # remove noisy stuff to make the output more terse for demo purpose
  # all the cleanup below here can be skipped
  grep -v newFuncRoot: | \
  sed 's/\(define.*)\).*/\1 {/' | \
  sed 's/, align.*//' | \
  sed 's/, !.*//' | \
  sed 's|call .*newpc(.*"revng.const.\([^"]*\)".*).*|call @newpc("\1")|' |
  sed 's/: *; preds.*/:/' | \
  sed 's|, "\*m,~{.*||' \
  > obfuscated.ll


# Apply -O2 optimization pipeline.
# This triggers inlining, constant propagation, and CFG simplification to remove
# dead branches, resulting in deobfuscated code.
zstdcat "${RESUME_DIRECTORY}"/cleanup-ir/module.bc.zstd | \
  # run O2 optimization pipeline, to deobfuscate the branch
  revng opt --enable-new-pm=true -O2 | \
  # extract the function we want, and some of its surrounding
  "${LLVM_EXTRACT}" --func="${FUNCTION}" -S | \
  grep define -A 1000000 | grep -B 10000 '^}' | \
  # remove noisy stuff to make the output more terse for demo purpose
  # all the cleanup below here can be skipped
  grep -v newFuncRoot: | \
  sed 's/\(define.*)\).*/\1 {/' | \
  sed 's/, align.*//' | \
  sed 's/, !.*//' | \
  sed 's|call .*newpc(.*"revng.const.\([^"]*\)".*).*|call @newpc("\1")|' |
  sed 's/: *; preds.*/:/' | \
  sed 's|, "\*m,~{.*||' \
  > deobfuscated.ll
